// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations and introspection should bypass the connection pooler.
    // Falls back to DATABASE_URL when DIRECT_URL is unset (e.g. Railway,
    // local dev) so single-URL setups still work.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
